# Generated by Django 6.0.5 on 2026-05-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futureApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='reset_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
